Fix Ruby tests, add rakefile

diff --git a/ruby/.scripts/test b/ruby/.scripts/test
--- a/ruby/.scripts/test
+++ b/ruby/.scripts/test
@@ -1,10 +1,6 @@
 #!/bin/sh
 
-for d in ${HOME}/exercism/ruby/*; do
-    (
-        cd "$d"
-        echo "==== ${d##*/} ===="
-        ruby *_test.rb
-        echo
-    )
-done
+cd "$(exercism workspace)/ruby" || {
+    >&2 echo "Could not cd to exercism Ruby workspace"
+}
+rake test
